spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8081

springdoc:
  swagger-ui:
    url: /open-api.yaml
openapi:
  aPIDocumentation:
    base-path: /school
