server:
  port: 9090
spring:
  application:
    name: school
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: always

