openapi: 3.0.2
info:
  title: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:9090/school/
tags:
  - name: School
    description: Endpoints for students and notes
paths:
  /subjectsWithStudents:
    get:
      tags:
        - School
      summary: Get all subjects with their students
      description: Returns a list of subjects with their associated students.
      operationId: getAllSubjectsWithStudents
      responses:
        200:
          description: A list of subjects with students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubjectResponseDto'
        404:
          description: Not Found - If the resource list is empty, return EMPTY_LIST.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        500:
          description: Internal Server Error - Use it as a General System Error, return INTERNAL_SERVER_ERROR.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /registered/generate-pdf:
    get:
      tags:
        - Registered
      summary: Generate a PDF with all registered records
      description: Returns a PDF containing all registered records encoded in Base64.
      operationId: generateAllRegisteredPdf
      responses:
        200:
          description: PDF encoded in Base64 with all registered records
          content:
            application/json:
              schema:
                type: object
                properties:
                  pdfBase64:
                    type: string
                    description: PDF file encoded in Base64
        500:
          description: Internal server error
  /allRegistrations:
    get:
      tags:
        - School
      summary: Get all registrations
      description: Returns a list of all registered entities.
      operationId: getAllRegistrations
      responses:
        200:
          description: A list of all registrations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegisteredResponseDto'
        404:
          description: Not Found - If the resource list is empty, return EMPTY_LIST.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        500:
          description: Internal Server Error - Use it as a General System Error, return INTERNAL_SERVER_ERROR.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
  /uploadNotes/{subjectId}:
    post:
      tags:
        - School
      summary: Record upload of grades of a subject to a student via Excel
      description: Register notes
      operationId: recordNotes
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the subject for which the notes are being uploaded.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        200:
          description: Student grades were uploaded successfully
        400:
          description: Bad Request - If the resource is misspelled (badly constructed URI) or if the data in the request is not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        500:
          description: Internal Server Error - Use it as a General System Error, return INTERNAL_SERVER_ERROR.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
components:
  schemas:
    # Properties
    studentName:
      type: string
      description: The name of the student
      example: John Doe
    ErrorObject:
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          description: Error message (detailed description)
          example: Invalid Request. Please, check the data in the request (QueryString Parameters and/or Body).
      description: Error details
      example:
        message: Invalid Request. Please, check the data in the request (QueryString Parameters and/or Body).
    SubjectResponseDto:
      type: object
      properties:
        subjectId:
          type: integer
          description: The ID of the subject
          example: 1
        subjectName:
          type: string
          description: The name of the subject
          example: Mathematics
        students:
          type: array
          items:
            $ref: '#/components/schemas/StudentDto'
    StudentDto:
      type: object
      required:
        - studentId
        - studentName
      properties:
        studentId:
          type: integer
          description: The ID of the student
          example: 123
        studentName:
          $ref: '#/components/schemas/studentName'
    RegisteredResponseDto:
      type: object
      required:
        - registeredId
        - studentName
        - documentNumber
        - subjectName
        - average
        - nota1
        - nota2
        - nota3
      properties:
        registeredId:
          type: integer
          description: The ID of the student
          example: 123
        studentName:
          $ref: '#/components/schemas/studentName'
        documentNumber:
          type: string
          description: The name of the student
          example: John Doe
        subjectName:
          type: string
          description: The name of the student
          example: John Doe
        average:
          type: number
          format: float
        nota1:
          type: number
          format: float
        nota2:
          type: number
          format: float
        nota3:
          type: number
          format: float

